In [131]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [173]:
data = pd.read_csv('train.csv')
df = pd.read_csv('test_submission.csv')
data.columns
data['floor'].unique()

data.shape

C:\Users\IVAN\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(279792, 77)

In [174]:
data.sample(30)

,city,floor,id,lat,lng,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,...,reform_mean_floor_count_1000,reform_mean_floor_count_500,reform_mean_year_building_1000,reform_mean_year_building_500,region,total_square,street,date,realty_type,price_type
232296,Новороссийск,NaN,COL_237329,44.732235,37.752403,0,18,45,64,0,...,5.454545,5.173913,1972.881818,1971.065217,Краснодарский край,32.0,S2911,2020-07-19,10,0
86707,Смоленск,NaN,COL_88734,54.771893,32.010000,0,8,26,44,0,...,6.512821,4.947368,1980.831933,1975.210526,Смоленская область,100.0,S6184,2020-03-08,10,0
13969,Москва,1.0,COL_14288,55.804190,37.513360,13,158,234,372,0,...,8.907143,8.900000,1960.750000,1959.520000,Москва,201.0,S13286,2020-01-12,110,0
39997,Новосибирск,2.0,COL_40927,54.857834,82.978310,0,12,28,36,0,...,5.369748,7.500000,1973.831933,1982.846154,Новосибирская область,96.0,S14818,2020-02-02,10,0
119389,Екатеринбург,NaN,COL_122133,56.826070,60.635460,2,58,123,197,0,...,7.079470,6.189655,1971.754967,1967.120690,Свердловская область,38.0,S6985,2020-04-12,10,0
11833,Красноярск,NaN,COL_12110,56.060894,92.952810,0,8,18,40,0,...,8.739130,8.000000,1987.869565,1985.129032,Красноярский край,111.0,S5845,2020-01-12,10,0
117953,"Новосибирский район, Краснообск рп, 6-й мкр",-1.0,COL_120663,54.929280,82.989860,0,0,5,13,0,...,6.280000,8.600000,1988.380000,2009.400000,Новосибирская область,400.0,S1545,2020-04-12,10,0
72311,Челябинск,NaN,COL_74022,55.164223,61.288216,3,14,35,69,0,...,11.513514,11.097561,2010.567568,2011.195122,Челябинская область,177.0,S2545,2020-03-01,10,0
100491,"Гурьевский городской округ, пос. Васильково",1.0,COL_102802,54.739998,20.580520,2,17,17,23,0,...,3.615385,4.357143,1984.156250,1994.740741,Калининградская область,96.0,S28585,2020-03-22,10,0
154425,Москва,1.0,COL_157958,55.737430,37.587666,11,151,315,464,0,...,6.675105,6.588235,1939.852321,1936.313725,Москва,352.0,S8151,2020-05-24,10,0
234775,Брянск,NaN,COL_239853,53.240670,34.324844,0,6,9,15,0,...,4.037037,3.600000,1970.777778,1978.600000,Брянская область,18.0,S28928,2020-07-26,110,0
218406,Химки,NaN,COL_223193,55.906730,37.255924,3,8,9,11,0,...,3.000000,NaN,1984.000000,NaN,Московская область,60.0,S8047,2020-07-12,110,0
148213,Дюртюли,1.0,COL_151618,55.474052,54.830100,0,0,0,0,0,...,NaN,NaN,NaN,NaN,Башкортостан,200.0,S2669,2020-05-17,110,0
271965,Санкт-Петербург,1.0,COL_277797,59.950290,30.265950,1,46,124,228,0,...,5.451220,10.000000,1924.108434,1980.666667,Санкт-Петербург,126.1,S27169,2020-08-23,10,0
180650,Арамиль,NaN,COL_184646,56.685825,60.855064,0,1,3,3,0,...,2.592593,3.500000,1981.225806,1986.200000,Свердловская область,184.0,S18486,2020-06-14,10,0
32146,Барнаул,NaN,COL_32882,53.340300,83.755910,0,17,68,94,0,...,5.600000,6.666667,1971.988235,1977.952381,Алтайский край,36.9,S14822,2020-01-26,10,0
268562,Красноярск,NaN,COL_274333,56.048847,92.977110,0,3,15,20,0,...,6.765432,7.303030,1973.109756,1974.323529,Красноярский край,103.0,S27137,2020-08-23,10,0
35667,Челябинск,NaN,COL_36495,55.180070,61.302113,2,68,107,191,0,...,11.333333,10.916667,1996.202020,1995.333333,Челябинская область,51.4,S1239,2020-02-02,10,0
35940,Екатеринбург,1.0,COL_36778,56.877136,60.620373,2,13,19,35,0,...,7.400000,6.800000,1973.885714,1970.900000,Свердловская область,735.0,S27477,2020-02-02,110,0
174111,Анапа,1.0,COL_178053,44.884350,37.324000,2,22,43,55,0,...,7.073770,7.689655,1993.434426,1999.655172,Краснодарский край,42.0,S32846,2020-06-07,10,0
204506,Краснодар,1.0,COL_208965,45.071644,39.010303,2,33,65,107,0,...,12.380952,15.480000,2004.273810,2013.040000,Краснодарский край,70.0,S8422,2020-06-28,110,0
252536,Кемерово,NaN,COL_257953,55.343967,86.181335,6,14,17,23,0,...,8.176471,8.842105,1982.970588,1985.263158,Кемеровская область,52.0,S10041,2020-08-09,110,0
229891,Екатеринбург,NaN,COL_234879,56.815872,60.615260,0,32,93,219,0,...,6.980392,6.806452,1972.162338,1976.193548,Свердловская область,266.2,S27968,2020-07-19,10,0
139179,Санкт-Петербург,1.0,COL_142375,59.982760,30.225767,0,11,40,75,0,...,16.200000,15.000000,2005.100000,2006.000000,Санкт-Петербург,105.3,S20184,2020-05-03,10,0
170308,Краснодар,1.0,COL_174149,45.028553,38.967040,5,105,242,362,0,...,2.170455,1.784946,1926.330206,1925.904762,Краснодарский край,40.0,S18486,2020-06-07,110,0
198155,Москва,NaN,COL_202497,55.550686,37.510450,0,0,5,16,0,...,10.937500,NaN,2001.437500,NaN,Москва,116.1,S20013,2020-06-21,10,0
154364,Набережные Челны,NaN,COL_157894,55.725533,52.374280,2,18,66,93,0,...,9.264151,7.833333,1999.471698,1991.833333,Татарстан,110.0,S2545,2020-05-24,10,0
11385,Москва,NaN,COL_11645,55.780148,37.452150,3,23,63,105,0,...,9.576577,10.969697,1972.981982,1976.878788,Москва,970.0,S14291,2020-01-12,10,0
225372,Москва,-1.0,COL_230268,55.835007,37.658337,5,57,104,154,0,...,9.731481,11.357143,1967.018519,1968.619048,Москва,349.0,S32174,2020-07-19,10,0
57337,Ишим,NaN,COL_58694,56.109790,69.456280,0,23,29,32,0,...,2.939394,2.916667,1970.727273,1971.833333,Тюменская область,133.0,S33512,2020-02-16,100,0

In [175]:
#тут я решил убрать признаки, которые отвечают за количество каких-либо точек в радиусе 1000, 750, 500 и 100 метров, 
#при этом создав новый признак, который является средним 

#создаем список признаков, которые нужно посчитать
cols_osm_amenity_points = [
                          'osm_amenity_points_in_0.001',
                          'osm_amenity_points_in_0.005', 
                          'osm_amenity_points_in_0.0075',
                          'osm_amenity_points_in_0.01', 
                           ]
data['osm_amenity_points'] = data[cols_osm_amenity_points].astype(float).mean(axis=1)  #создаем новый столбец и присваиваем ему значения среднего тех признаков, которые мы указали выше
data = data.drop(columns=cols_osm_amenity_points)  #удаляем 4 столба

cols_osm_building_points = [
                          'osm_building_points_in_0.001',
                          'osm_building_points_in_0.005', 
                          'osm_building_points_in_0.0075',
                          'osm_building_points_in_0.01', 
                           ]
data['osm_building_points'] = data[cols_osm_building_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_building_points)

cols_osm_catering_points = [
                          'osm_catering_points_in_0.001',
                          'osm_catering_points_in_0.005', 
                          'osm_catering_points_in_0.0075',
                          'osm_catering_points_in_0.01',  
                           ]
data['osm_catering_points'] = data[cols_osm_catering_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_catering_points)

cols_osm_crossing_points = [
    'osm_crossing_points_in_0.001',
    'osm_crossing_points_in_0.005', 
    'osm_crossing_points_in_0.0075',
    'osm_crossing_points_in_0.01',  
                           ]
data['osm_crossing_points'] = data[cols_osm_crossing_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_crossing_points)

cols_osm_culture_points = [
    'osm_culture_points_in_0.001',
    'osm_culture_points_in_0.005', 
    'osm_culture_points_in_0.0075',
    'osm_culture_points_in_0.01',  
                           ]
data['osm_culture_points'] = data[cols_osm_culture_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_culture_points)

cols_osm_finance_points = [
    'osm_finance_points_in_0.001',
    'osm_finance_points_in_0.005', 
    'osm_finance_points_in_0.0075',
    'osm_finance_points_in_0.01',   
                           ]
data['osm_finance_points'] = data[cols_osm_finance_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_finance_points)

cols_osm_healthcare_points = [
    'osm_healthcare_points_in_0.005',
    'osm_healthcare_points_in_0.0075', 
    'osm_healthcare_points_in_0.01',   
                           ]
data['osm_healthcare_points'] = data[cols_osm_healthcare_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_healthcare_points)

cols_osm_historic_points = [
    'osm_historic_points_in_0.005', 
    'osm_historic_points_in_0.0075',
    'osm_historic_points_in_0.01',   
                           ]
data['osm_historic_points'] = data[cols_osm_historic_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_historic_points)

cols_osm_hotels_points = [
    'osm_hotels_points_in_0.005',
    'osm_hotels_points_in_0.0075', 
    'osm_hotels_points_in_0.01', 
                           ]
data['osm_hotels_points'] = data[cols_osm_hotels_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_hotels_points)

cols_osm_leisure_points = [
    'osm_leisure_points_in_0.005', 
    'osm_leisure_points_in_0.0075',
    'osm_leisure_points_in_0.01', 
                           ]
data['osm_leisure_points'] = data[cols_osm_leisure_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_leisure_points)

cols_osm_offices_points = [
    'osm_offices_points_in_0.001',
    'osm_offices_points_in_0.005', 
    'osm_offices_points_in_0.0075',
    'osm_offices_points_in_0.01', 
                           ]
data['osm_offices_points'] = data[cols_osm_offices_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_offices_points)

cols_osm_shops_points = [
    'osm_shops_points_in_0.001',
    'osm_shops_points_in_0.005', 
    'osm_shops_points_in_0.0075',
    'osm_shops_points_in_0.01', 
                           ]
data['osm_shops_points'] = data[cols_osm_shops_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_shops_points)

cols_osm_train_stop_points = [
    'osm_train_stop_points_in_0.005',
    'osm_train_stop_points_in_0.0075', 
    'osm_train_stop_points_in_0.01',
                           ]
data['osm_train_stop_points'] = data[cols_osm_train_stop_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_train_stop_points)

cols_osm_transport_stop_points = [
    'osm_transport_stop_points_in_0.005',
    'osm_transport_stop_points_in_0.0075',
    'osm_transport_stop_points_in_0.01', 
                           ]
data['osm_transport_stop_points'] = data[cols_osm_transport_stop_points].astype(float).mean(axis=1)
data = data.drop(columns=cols_osm_transport_stop_points)

cols_reform_count_of_houses = [
    'reform_count_of_houses_1000', 
    'reform_count_of_houses_500',
                           ]
data['reform_count_of_houses'] = data[cols_reform_count_of_houses].astype(float).mean(axis=1)
data = data.drop(columns=cols_reform_count_of_houses)

cols_reform_house_population = [
    'reform_house_population_1000', 
    'reform_house_population_500',
                           ]
data['reform_house_population'] = data[cols_reform_house_population].astype(float).mean(axis=1)
data = data.drop(columns=cols_reform_house_population)

cols_reform_mean_floor_count = [
    'reform_mean_floor_count_1000', 
    'reform_mean_floor_count_500',
                           ]
data['reform_mean_floor_count'] = data[cols_reform_mean_floor_count].astype(float).mean(axis=1)
data = data.drop(columns=cols_reform_mean_floor_count)

cols_reform_mean_year_building = [
    'reform_mean_year_building_1000', 
    'reform_mean_year_building_500',
                           ]
data['reform_mean_year_building'] = data[cols_reform_mean_year_building].astype(float).mean(axis=1)
data = data.drop(columns=cols_reform_mean_year_building)

In [135]:
cols = [
            'floor', 
            'lat', 
            'lng', 
            'osm_city_closest_dist',
            'osm_city_nearest_name', 
            'osm_city_nearest_population',
        
            'osm_crossing_closest_dist', 
            'osm_subway_closest_dist',
            'osm_train_stop_closest_dist', 
            'osm_transport_stop_closest_dist', 
        
            'region', 
            'total_square', 
            'street', 
    ]

mean_cols = [  
             'osm_amenity_points',
             'osm_building_points',
             'osm_catering_points',
             'osm_crossing_points',
             'osm_culture_points',
             'osm_finance_points',
             'osm_healthcare_points',
             'osm_historic_points',
             'osm_hotels_points',
             'osm_leisure_points',
             'osm_offices_points',
             'osm_shops_points',
             'osm_train_stop_points',
             'osm_transport_stop_points',
             'reform_count_of_houses',
             'reform_house_population',
             'reform_mean_floor_count',
             'reform_mean_year_building',
]

# 1.Чистка данных

In [230]:
#оптимизируем данные
full_data = data.drop(columns='floor').dropna()

full_data.columns
full_data['floor'] = data['floor']

In [231]:
data.isna().sum()
data.head()

data['floor'] = data['floor'].astype('str')

# Функция из Nan в 1 этаж
def fromNaN(x):
    if x == 'nan' or x == '1.0':
        x = '1'
    elif x == 'цоколь' or x == 'подвал' or x =='цоколь':
        x = '-1'
    elif x == '-1.0':
        x = '-1'
    return x 

# Функция оптимизации))
def checkseq(y):
    if 'цоколь'  in y:
        y = '-1'
    elif 'подвал'  in y:
        y = '-1'
    elif 'Подвал'  in y:
        y = '-1'
    elif 'Цоколь'  in y:
        y = '-1'
    
    return y 

# Используем фуннкцию fromNan для столбца floor
data['floor'] = data['floor'].map(fromNaN)
data['floor'] = data['floor'].map(checkseq)

In [232]:

data['floor'].replace(0, -1, inplace=True)  #заменил нулевые этажи на -1 , так как в данных есть как нулевые этажи, так и -1, хотя это одно и то же как по мне

In [233]:
# Удаляем строки, в которых есть слова
data = data.drop(data[(data['floor'].map(len) > 5)].index) # алгоритм работает после перезагрузки дф

In [234]:
# Удаляем строки, запись которых имеет вид  '4, 6 ', '1-й' и тд.
data = data.drop(data[(data['floor'] == '1, 2')].index)
data['floor'].unique()

array(['1', '3.0', '4.0', '-1', '14.0', '2.0', '8.0', '-2.0', '6.0',
       '10.0', '5.0', '16.0', '19.0', '7.0', '9.0', '58.0', '24.0',
       '18.0', '26.0', '17.0', '48.0', '11.0', '-3.0', '15.0', '22.0',
       '60.0', '12.0', '21.0', '35.0', '28.0', '38.0', '39.0', '13.0',
       '81.0', '44.0', '82.0', '25.0', '45.0', '47.0', '23.0', '37.0',
       '29.0', '113.0', '78.0', '42.0', '69.0', '27.0', '46.0', '53.0',
       '80.0', '70.0', '76.0', '64.0', '30.0', '73.0', '77.0', '52.0',
       '67.0', '65.0', '20.0', '40.0', '49.0', '75.0', '93.0', '94.0',
       '91.0', '72.0', '79.0', '84.0', '92.0', '33.0', '66.0', '90.0',
       '31.0', '36.0', '61.0', '71.0', '68.0', '51.0', '97.0', '43.0',
       '95.0', '85.0', '50.0', '0.0', '62.0', '54.0', '74.0', '57.0',
       '41.0', '34.0', '59.0', '56.0', '123.0', '55.0', '83.0'],
      dtype=object)

In [235]:
data['floor'].unique()

array(['1', '3.0', '4.0', '-1', '14.0', '2.0', '8.0', '-2.0', '6.0',
       '10.0', '5.0', '16.0', '19.0', '7.0', '9.0', '58.0', '24.0',
       '18.0', '26.0', '17.0', '48.0', '11.0', '-3.0', '15.0', '22.0',
       '60.0', '12.0', '21.0', '35.0', '28.0', '38.0', '39.0', '13.0',
       '81.0', '44.0', '82.0', '25.0', '45.0', '47.0', '23.0', '37.0',
       '29.0', '113.0', '78.0', '42.0', '69.0', '27.0', '46.0', '53.0',
       '80.0', '70.0', '76.0', '64.0', '30.0', '73.0', '77.0', '52.0',
       '67.0', '65.0', '20.0', '40.0', '49.0', '75.0', '93.0', '94.0',
       '91.0', '72.0', '79.0', '84.0', '92.0', '33.0', '66.0', '90.0',
       '31.0', '36.0', '61.0', '71.0', '68.0', '51.0', '97.0', '43.0',
       '95.0', '85.0', '50.0', '0.0', '62.0', '54.0', '74.0', '57.0',
       '41.0', '34.0', '59.0', '56.0', '123.0', '55.0', '83.0'],
      dtype=object)

In [236]:
# Преобразуем все значения столбца floor в вещественный тип 
data['floor'] = data['floor'].astype('float')
data['floor'].unique()

array([  1.,   3.,   4.,  -1.,  14.,   2.,   8.,  -2.,   6.,  10.,   5.,
        16.,  19.,   7.,   9.,  58.,  24.,  18.,  26.,  17.,  48.,  11.,
        -3.,  15.,  22.,  60.,  12.,  21.,  35.,  28.,  38.,  39.,  13.,
        81.,  44.,  82.,  25.,  45.,  47.,  23.,  37.,  29., 113.,  78.,
        42.,  69.,  27.,  46.,  53.,  80.,  70.,  76.,  64.,  30.,  73.,
        77.,  52.,  67.,  65.,  20.,  40.,  49.,  75.,  93.,  94.,  91.,
        72.,  79.,  84.,  92.,  33.,  66.,  90.,  31.,  36.,  61.,  71.,
        68.,  51.,  97.,  43.,  95.,  85.,  50.,   0.,  62.,  54.,  74.,
        57.,  41.,  34.,  59.,  56., 123.,  55.,  83.])

In [237]:
data

,city,floor,id,lat,lng,osm_city_closest_dist,osm_city_nearest_name,osm_city_nearest_population,osm_crossing_closest_dist,osm_subway_closest_dist,...,osm_hotels_points,osm_leisure_points,osm_offices_points,osm_shops_points,osm_train_stop_points,osm_transport_stop_points,reform_count_of_houses,reform_house_population,reform_mean_floor_count,reform_mean_year_building
0,3062,1.0,COL_0,57.998207,56.292797,3.293470,109,1055397.0,0.027732,269.024986,...,0.000000,1.000000,1.75,15.75,0.0,12.666667,92.5,1634.0,5.646788,1962.538851
1,4440,1.0,COL_1,55.574284,39.543835,43.950989,104,120184.0,0.089441,102.455451,...,2.000000,1.333333,1.50,15.50,0.0,8.333333,91.5,925.0,3.211072,1954.771950
2,4613,1.0,COL_2,57.619140,39.850525,2.676293,167,603961.0,0.200995,243.361937,...,0.333333,3.666667,4.00,33.50,0.0,14.333333,66.0,1228.0,6.681818,1970.760185
3,2682,1.0,COL_3,53.897083,87.108604,15.618563,89,552105.0,0.861400,295.633502,...,0.000000,0.333333,0.00,3.75,0.0,1.000000,38.5,927.5,8.790541,2003.358108
4,2464,1.0,COL_4,55.802590,37.487110,9.995325,156,232066.0,0.236744,1.110429,...,1.666667,5.333333,7.00,32.50,0.0,34.666667,91.0,1854.5,6.474050,1961.864583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279787,3962,1.0,COL_280111,56.459183,84.979334,3.614641,147,576624.0,0.116917,201.668316,...,4.000000,6.000000,1.75,53.25,0.0,20.666667,130.0,1993.5,5.798319,1972.860435
279788,3415,1.0,COL_280479,59.936954,30.356383,2.063594,125,5381736.0,0.110570,0.748926,...,84.000000,23.666667,72.25,315.25,0.0,39.333333,245.0,4660.0,4.713027,1875.090782
279789,1497,3.0,COL_280518,54.729233,20.514968,2.126417,48,453461.0,0.108723,814.733428,...,2.333333,1.333333,4.25,17.00,0.0,18.666667,86.5,842.5,4.418064,1967.414881
279790,1586,1.0,COL_280529,55.360680,86.081460,0.844577,52,558662.0,0.341931,200.109079,...,0.333333,4.000000,5.75,26.00,0.0,11.666667,59.0,1039.0,4.408245,1956.025266
279791,1640,1.0,COL_280637,58.592915,49.677439,1.317512,54,496986.0,0.126115,306.460323,...,1.666667,2.000000,2.75,27.25,0.0,11.666667,164.0,1750.5,4.922622,1972.196598

In [276]:
# Закодируем названия городов 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['city'] = le.fit_transform(data['city'])
data['osm_city_nearest_name'] = le.fit_transform(data['osm_city_nearest_name'])
data['region'] = le.fit_transform(data['region'])
data['street'] = le.fit_transform(data['street'])

In [278]:
# Добавим к фулл дате названия городов и этажи, заменим улицу и регион

full_data['floor'] = data['floor']
full_data['region'] = data['region']
full_data['street'] = data['street']
full_data.columns

Index(['city', 'lat', 'lng', 'osm_city_closest_dist', 'osm_city_nearest_name',
       'osm_city_nearest_population', 'osm_crossing_closest_dist',
       'osm_subway_closest_dist', 'osm_train_stop_closest_dist',
       'osm_transport_stop_closest_dist', 'region', 'total_square', 'street',
       'realty_type', 'price_type', 'osm_amenity_points',
       'osm_building_points', 'osm_catering_points', 'osm_crossing_points',
       'osm_culture_points', 'osm_finance_points', 'osm_healthcare_points',
       'osm_historic_points', 'osm_hotels_points', 'osm_leisure_points',
       'osm_offices_points', 'osm_shops_points', 'osm_train_stop_points',
       'osm_transport_stop_points', 'reform_count_of_houses',
       'reform_house_population', 'reform_mean_floor_count',
       'reform_mean_year_building', 'floor', 'per_square_meter_price'],
      dtype='object')

### Конечный датафрэйм

In [280]:

full_data.columns

Index(['city', 'lat', 'lng', 'osm_city_closest_dist', 'osm_city_nearest_name',
       'osm_city_nearest_population', 'osm_crossing_closest_dist',
       'osm_subway_closest_dist', 'osm_train_stop_closest_dist',
       'osm_transport_stop_closest_dist', 'region', 'total_square', 'street',
       'realty_type', 'price_type', 'osm_amenity_points',
       'osm_building_points', 'osm_catering_points', 'osm_crossing_points',
       'osm_culture_points', 'osm_finance_points', 'osm_healthcare_points',
       'osm_historic_points', 'osm_hotels_points', 'osm_leisure_points',
       'osm_offices_points', 'osm_shops_points', 'osm_train_stop_points',
       'osm_transport_stop_points', 'reform_count_of_houses',
       'reform_house_population', 'reform_mean_floor_count',
       'reform_mean_year_building', 'floor', 'per_square_meter_price'],
      dtype='object')

In [ ]:
full_data = full_data.drop('per_square_meter_price', axis = 1)

In [281]:


full_data = full_data.drop(['date','id'], axis = 1)
full_data

KeyError: "['date' 'id'] not found in axis"

In [291]:
full_data['per_square_meter_price'] = data['per_square_meter_price']
full_data[['region','street']] = full_data[['region','street']].astype('int64')


full_data = full_data.astype('int64')

In [295]:
full_data

,city,lat,lng,osm_city_closest_dist,osm_city_nearest_name,osm_city_nearest_population,osm_crossing_closest_dist,osm_subway_closest_dist,osm_train_stop_closest_dist,osm_transport_stop_closest_dist,...,osm_offices_points,osm_shops_points,osm_train_stop_points,osm_transport_stop_points,reform_count_of_houses,reform_house_population,reform_mean_floor_count,reform_mean_year_building,floor,per_square_meter_price
0,3062,57,56,3,109,1055397,0,269,3,0,...,1,15,0,12,92,1634,5,1962,1,139937
1,4440,55,39,43,104,120184,0,102,1,0,...,1,15,0,8,91,925,3,1954,1,60410
2,4613,57,39,2,167,603961,0,243,1,0,...,4,33,0,14,66,1228,6,1970,1,45164
3,2682,53,87,15,89,552105,0,295,9,1,...,0,3,0,1,38,927,8,2003,1,28805
4,2464,55,37,9,156,232066,0,1,1,0,...,7,32,0,34,91,1854,6,1961,1,13222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279787,3962,56,84,3,147,576624,0,201,0,0,...,1,53,0,20,130,1993,5,1972,1,54278
279788,3415,59,30,2,125,5381736,0,0,1,0,...,72,315,0,39,245,4660,4,1875,1,595298
279789,1497,54,20,2,48,453461,0,814,1,0,...,4,17,0,18,86,842,4,1967,3,35758
279790,1586,55,86,0,52,558662,0,200,2,0,...,5,26,0,11,59,1039,4,1956,1,38755
279791,1640,58,49,1,54,496986,0,306,1,0,...,2,27,0,11,164,1750,4,1972,1,41335

# 2.Применяем алгоритмы
## 2.1 Случаный лес

In [1]:
# не успел доделать (: